config/routes.rb
Rails.application.routes.draw do
  get 'pokemon_cards/index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/welcome', to: 'home#index'

  get '/data', to: 'data#index'

  get '/navbar', to: 'navbar#index'

  get '/alumnos', to: 'alumnos#index'

  get 'form', to: 'form#index'

  get '/pokemon', to: 'pokemon_cards#index'

  get '/healthcheck', to: 'healthcheck#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon_card.rb
class PokemonCard < ApplicationRecord
    validates :name, uniqueness: true
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
    def index 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/data_controller.rb
class DataController < ApplicationController
    def index
    end
end

app/controllers/form_controller.rb
class FormController < ApplicationController
    def index
    end
end

app/controllers/healthcheck_controller.rb
class HealthcheckController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/navbar_controller.rb
class NavbarController < ApplicationController
    def _index
    end
end

app/controllers/pokemon_cards_controller.rb
class PokemonCardsController < ApplicationController
  def index
    if PokemonCard.count == 0
    response = HTTParty.get("https://pokeapi.co/api/v2/pokemon/")
    data = JSON.parse(response.body)

    data['results'].each do |pokemon|
      name = pokemon['name']
      image_url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/#{pokemon['url'].split('/').last}.png"
      
      PokemonCard.create(name: name, image_url: image_url)
    end
  end
  @pokemon_cards = PokemonCard.all
end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/healthcheck_helper.rb
module HealthcheckHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
end

app/helpers/pokemon_cards_helper.rb
module PokemonCardsHelper
end

app/views/alumnos/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

app/views/data/index.html.erb
<h1> Hello world desde data </h1>

app/views/form/index.html.erb
<div class="container">
<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

app/views/healthcheck/index.html.erb
<h1> hola desde healthcheck</h1>

app/views/home/index.html.erb
<h1>Hello world</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'navbar/index' %>
    <%= yield %>
  </body>
</html>

app/views/navbar/_index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <a class="navbar-brand" <%= link_to 'Inicio', welcome_path %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" <%= link_to 'Datos', data_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to 'alumnos', alumnos_path %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" <%= link_to 'Formulario', form_path %> </a></li>
            <li><a class="dropdown-item"  <%= link_to 'Pokemons', pokemon_path %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/navbar/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <a class="navbar-brand" "<%= link_to 'Inicio', welcome_path %>"</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/pokemon_cards/index.html.erb
<h1 class="bg-warning text-center">Tarjetas Pokémon</h1>

<div class="pokemon-cards row">
  <% @pokemon_cards.each do |pokemon_card| %>
    <div class="pokemon-card border border-black col-12 col-sm-6 col-md-4 d-flex flex-row justify-content-center align-items-center">
      <h2> <%= pokemon_card.name %></h2>
      <img src="<%= pokemon_card.image_url %>" alt="<%= pokemon_card.name %>">
    </div>
  <% end %>
</div>